Feature/homework
YuliiaPetrenko66/js-lecture pull request #2
Opened 2023-06-14 15:44 UTC by YuliiaPetrenko66

2023-06-14 19:07 UTC, SanitarskyiDmytro requested changes

2023-06-14 19:07 UTC, SanitarskyiDmytro commented on hw.js
> +console.log('Результат видалення голосних букв зі слова "Індустріалізація": ' + '"' + newResult + '"');
Це не помилка, але краще ось так зробити:

```console.log(`Результат видалення голосних букв зі слова  ${str}:  ${newResult} `);```

2023-06-14 19:07 UTC, SanitarskyiDmytro commented on hw.js
> +console.log(km());
вивід в консоль має бути в такому форматі:

`1000 метрів це 1 кілометр
`

це трошки ускладнює рішення)

2023-06-14 20:26 UTC, YuliiaPetrenko66 commented on hw.js
> +console.log('Результат видалення голосних букв зі слова "Індустріалізація": ' + '"' + newResult + '"');
Дякую

2023-06-14 20:26 UTC, YuliiaPetrenko66 commented on hw.js
> +console.log(km());
З умови не зрозуміла, що потрібно зробити конкретний вивід. Буду думати)

2023-06-19 07:44 UTC, SanitarskyiDmytro approved these changes

2023-06-19 15:52 UTC, merged